# Generated by Django 6.0.2 on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenCartConnectionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="opencart",
                        max_length=80,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("waiting", "Waiting"),
                            ("disconnected", "Disconnected"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField(blank=True)),
                ("catalog_items", models.PositiveIntegerField(default=0)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "OpenCart connection",
                "verbose_name_plural": "OpenCart connection",
            },
        ),
    ]
