# Generated by Django 6.0.2 on 2026-06-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_app', '0002_opencartconnectionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
