# Generated by Django 6.0.2 on 2026-06-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_app', '0003_conversation_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='api_key',
        ),
    ]
